[build-system]
requires = ["hatchling >= 1.27"]
build-backend = "hatchling.build"

[project]
name = "zapmenot"
dynamic = ["version"]
description = "Library of routines for performing point kernel photon shielding calculations."
readme = "README.rst"
license = "GPL-3.0-or-later"
authors = [
    {name = "Alan Ford"}
]
classifiers = [
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering"
]
license-files = ["LICEN[CS]E*", "vendored/licenses/*.txt", "AUTHORS.md"]
requires-python = ">=3.11.14"
dependencies = [
  # basic functionality
  "scipy",
  "pyyaml",
  "pyvista>=0.45",
]

[dependency-groups]
dev = [
    "hatch",
    "sphinx >=8.2",
    "sphinx-rtd-theme >=3.0",
    "sphinx-autodoc-typehints>=3.6.1",
    "typing-extensions>=4.15.0",
    "flake8 >=7.2",
    "build >=1.2",
    "types-PyYAML",
    "scipy-stubs",
    ]
# include by using: uv sync --group jupyterlab
jupyterlab = [
    "zapmenot[jupyterlab]"
]
# include by using: uv sync --group test
test = [
    "zapmenot[test]"
]

[project.optional-dependencies]
jupyterlab = [
  # jupyterlab, including headless
  "jupyterlab >=4.5.9",
  "trame >=3.10",
  "trame-vtk >=2.8.17",
  "trame-vuetify >=3.0",
  "ipywidgets >=8.1.7",
]
test = [
    "pandas>=2.3",
    "pytest>=9.0.3",
]


[project.urls]
Homepage = "https://github.com/AlanFord/ZapMeNot"

[tool.hatch.version]
path = "src/zapmenot/__about__.py"

[tool.hatch.build.targets.sdist]
exclude = [
  "/.github",
  "/dist",
  "/references",
  "/docs",
]

[tool.hatch.build.targets.wheel]
packages = ["src/zapmenot", "tests", "benchmarks", "docs",
  "LICENSE", "pytest.ini", "README.rst"]
exclude = ["/dist"]

[tool.uv.sources]
zapmenot = { workspace = true }

